name: CI for Flask Product API

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    types: [ opened, synchronize ]
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Clone the project
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Install the software (Python 3.10)
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Download dependencies
        run: |
          pip install --only-binary :all: -r requirements.txt

      - name: Initialize DB
        run: python db.py -a

      - name: Run unit tests
        run: echo "No tests defined yet"

      - name: Run SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v5.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          with:
          args: >
            -Dsonar.organization=marjanaL
            -Dsonar.projectKey=marjanaL_python-app-marjanaL
